version: '2'
services:
    showcases-app:
        image: showcases
        external_links:
            - showcases-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ShowCases
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    showcases-mongodb:
        extends:
            file: mongodb.yml
            service: showcases-mongodb
