version: '2'
services:
    showcases-mongodb:
        container_name: showcases-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/ShowCases/mongodb/:/data/db/
